# -*- coding: utf-8 -*-
"""Walmart_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kPCIG18iGWt72rdoL4lp1BTxr7HudFgN
"""

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns

import statsmodels.api as sm

import math

import datetime

import warnings
warnings.filterwarnings('ignore')

from math import sqrt

from scipy import stats

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Walmart Project/Walmart_Dataset.csv")

df.shape

df.columns

df.info()

# Change Store column to categorical type
df['Store'] = df.Store.astype('category')

# Change Holiday_Flag column to boolean type
df['Holiday_Flag'] = df['Holiday_Flag'].astype(bool)

# Change Date columns to datetime type
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%Y")

df['Year'] =df['Date'].dt.year
df['Month'] =df['Date'].dt.month
df['Week'] =df['Date'].dt.isocalendar().week

df.head()

df.tail()

df.info()

df.isnull().sum()

df.isnull()

# Exclude datetime column(s) from mean imputation
mean_imputation_cols = df.columns.drop(['Date'])

# The df.isnull().sum() output from a previous cell indicates that there are no missing values in the DataFrame,
# making the df.fillna() operation unnecessary.
# df.fillna(df.mean(), inplace=True)

# Check the number of missing values in each column
df.isnull().sum()

# Check for duplicate rows
df.duplicated().sum()  # Count the number of duplicate rows

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Check for duplicate columns
df.columns.duplicated().sum()  # Count the number of duplicate columns

# Remove duplicate columns, if any
df = df.loc[:, ~df.columns.duplicated()]

Q1 = df['Weekly_Sales'].quantile(0.25)
Q3 = df['Weekly_Sales'].quantile(0.75)
IQR = Q3 - Q1
outlier_threshold = 1.5 * IQR

df = df[(df['Weekly_Sales'] >= Q1 - outlier_threshold) & (df['Weekly_Sales'] <= Q3 + outlier_threshold)]

"""# EDA"""

df.describe()

"""Min Date & Max Date"""

print('Min Date in Data is - {}'.format(df['Date'].min()))
print('Max Date in Data is - {}'.format(df['Date'].max()))

# Scatter plot to explore the relationship between weekly sales and unemployment rate
plt.figure(figsize=(20, 5))
sns.scatterplot(x='Weekly_Sales', y='Unemployment', data=df)

# Set the title
plt.title('Correlation between Weekly Sales and Unemployment', color='#007DC6', fontsize=20, pad=10)

# Set the x and y axis labels
plt.xlabel('Weekly Sales', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Unemployment', color='#F1C21B',  fontweight='bold', fontsize=14)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

# Calculate the correlation coefficient between weekly sales and unemployment rate
correlation_coefficient = df['Weekly_Sales'].corr(df['Unemployment'])
print("Correlation Coefficient Between Weekly Sales and Unemployment Rate:", correlation_coefficient)

# Calculate the correlation between each store's weekly sales and unemployment rate
store_correlation = df.groupby('Store')[['Weekly_Sales', 'Unemployment']].corr().unstack()

# Find stores with the highest negative correlation
stores_with_highest_negative_correlation = store_correlation['Weekly_Sales']['Unemployment'].idxmin()

print("Stores with the Highest Negative Correlation with Unemployment Rate:", stores_with_highest_negative_correlation)

# Find the top N number of stores with the highest negative correlation
n = 10  # specify the number of stores to display, you can modify this value

print("Top", n, "Stores with the Highest Negative Correlation with Unemployment Rate:")

print()

top_negative_corr_stores = store_correlation['Weekly_Sales']['Unemployment'].sort_values().head(n)

# Create a dataframe
top_negative_corr_stores_df = pd.DataFrame({'Store': top_negative_corr_stores.index, 'Negative_Correlation': top_negative_corr_stores.values})

# Set the index to start from 1
top_negative_corr_stores_df.index = top_negative_corr_stores_df.index + 1

print(top_negative_corr_stores_df.to_string(index=False))

"""---

How Holidays affect the sales of each store.
"""

# impact of holidays on weekly sales
plt.figure(figsize = (12,8))
sns.boxplot(x = 'Holiday_Flag', y ='Weekly_Sales', data = df, showfliers = False)

# Mapping 0 to False and 1 to True in x-axis labels
plt.xticks([0, 1], ['False', 'True'])

plt.show()

"""Data Visualization"""

# Analyzing the distribution of target variable
plt.figure(figsize = (10, 5))
sns.distplot(df['Weekly_Sales'], hist_kws=dict(edgecolor="black"))
plt.title('Weekly Sales Distribution', fontsize= 15)
plt.grid()
plt.show()

"""Histogram of Weekly Sales"""

# Set the size of the graph
plt.figure(figsize=(10, 6))

# Plot a histogram of the 'Weekly_Sales' column from the DataFrame
plt.hist(df['Weekly_Sales'], bins=20)

# Set the x and y labels with specified colors, font weight, and font size
plt.xlabel('Weekly Sales', color='#F1C21B', fontweight='bold', fontsize=14)
plt.ylabel('Frequency', color='#F9AB00', fontweight='bold', fontsize=14)

# Set the title with specified color, font style, font size, and padding
plt.title('Distribution of Weekly Sales', color='#007DC6', fontsize=20, pad=20)

# Adjust plot appearance and layout
plt.tight_layout()

# Display the plot
plt.show()

df.groupby('Month')['Weekly_Sales'].mean()

df.groupby('Year')['Weekly_Sales'].mean()

df['Holiday_Flag'].value_counts()

"""**Relation between a categorized feature and the Weekly_Sales**

"""

def graph_relation_to_weekly_sale(col_relation, df, x='Week', palette=None):
    cmap = sns.diverging_palette(220, 20, as_cmap=True)

    sns.relplot(
        x=x,
        y='Weekly_Sales',
        hue=col_relation,
        data=df,
        kind='line',
        height=5,
        aspect=2,
        palette=palette
    )
    plt.show()

graph_relation_to_weekly_sale('Year', df, x='Date', palette='Set2')

"""Average Weekly Sales"""

plt.figure(figsize=(20, 7))
sns.barplot(x='Week', y='Weekly_Sales', data=df)
plt.title('Average Weekly Sales', fontsize=18)
plt.ylabel('Weekly Sales', fontsize=16)
plt.xlabel('Week', fontsize=16)
plt.grid()
plt.show()

"""Box plot of Weekly Sales by Store"""

plt.figure(figsize=(20, 8))

# Plot the boxplot
sns.boxplot(x='Store', y='Weekly_Sales', data=df)

# Set the x and y labels with Walmart font colors
plt.xlabel('Store', color='#007DC6', fontweight='bold', fontsize=20)
plt.ylabel('Weekly Sales', color='#F1C21B', fontweight='bold', fontsize=20)

# Set the title with Walmart font colors
plt.title('Distribution of Weekly Sales by Store', color='#2FB12C', fontsize=30, pad=20)

# Set the font size for x-axis labels
plt.xticks(fontsize=10)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

"""Heatmap"""

plt.figure(figsize=(20, 10))
sns.heatmap(df.corr(), cmap='PuBu', annot=True)
plt.title('Correlation Matrix',fontsize=16)
plt.show()

"""# Correlation Graph"""

# Correlation between Unemployment & Store
plt.figure(figsize=(20, 5))
sns.set_theme(style="whitegrid")
ax = sns.barplot(x='Store', y="Unemployment", data=df)

# Set the title
plt.title('Correlation Between Unemployment & Store', color='#007DC6', fontsize=20, pad=10)

# Set the x and y axis labels
plt.xlabel('Store', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Weekly Sales', color='#F1C21B',  fontweight='bold', fontsize=14)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

# Correlation between Weekly Sales & Store
plt.figure(figsize=(20, 5))
sns.set_theme(style="whitegrid")
ax = sns.barplot(x='Store', y="Weekly_Sales", data=df)

# Set the title
plt.title('Correlation Between Weekly Sales & Store', color='#007DC6', fontsize=20, pad=10)

# Set the x and y axis labels
plt.xlabel('Store', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Weekly Sales', color='#F1C21B',  fontweight='bold', fontsize=14)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

# Correlation b/w Fuel_Price & Year
plt.figure(figsize=(20, 5))
sns.set_theme(style="whitegrid")
ax = sns.barplot(x="Year", y="Fuel_Price", data=df)
sns.set(rc = {'figure.figsize': (10,4)})

# Set the title
plt.title('Correlation Between Fuel Price & Year', color='#007DC6', fontsize=20, pad=10)

# Set the x and y axis labels
plt.xlabel('Year', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Fuel Price', color='#F1C21B', fontweight='bold',fontsize=14)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

# Correlation between Weekly Sales & Month
plt.figure(figsize=(20, 5))
sns.set_theme(style="whitegrid")
month_wise_sales = df.pivot_table(values="Weekly_Sales", columns="Year", index="Month")
month_wise_sales.plot(marker='o')

# Set the title with Walmart font colors
plt.title('Correlation Between Weekly Sales and Month', color='#007DC6', fontsize=16, pad=10)

# Set the x and y labels with Walmart font colors
plt.xlabel('Month', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Weekly Sales', color='#F1C21B',  fontweight='bold', fontsize=14)

# Adjust plot layout
plt.legend(loc='upper left')
plt.tight_layout()

# Display the plot
plt.show()

# Correlation between Unemployment & Store
plt.figure(figsize=(20, 5))
sns.set_theme(style="whitegrid")

# Draw Scatterplot
sns.scatterplot(x="Store", y="Unemployment", data=df)

# Set the title
plt.title('Correlation Between Unemployment & Store', color='#007DC6', fontsize=20, pad=10)

# Set the x and y axis labels
plt.xlabel('Store', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Unemployment', color='#F1C21B',  fontweight='bold', fontsize=14)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

# Scatter plot of Weekly Sales vs. Temperature
plt.figure(figsize=(10, 6))

# Plot the scatter plot
sns.scatterplot(x="Temperature", y="Weekly_Sales", data=df)

# Set the title with Walmart font colors
plt.title('Correlation Between Weekly Sales & Temperature', color='#007DC6', fontsize=16, pad=10)

# Set the x and y labels with Walmart font colors
plt.xlabel('Temperature', color='#F1C21B',  fontweight='bold', fontsize=14)
plt.ylabel('Weekly Sales', color='#F1C21B',  fontweight='bold', fontsize=14)

# Set the font size for x-axis labels
plt.xticks(fontsize=10)

# Adjust plot layout
plt.tight_layout()

# Display the plot
plt.show()

from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor

from xgboost import XGBRegressor

from sklearn import tree
from sklearn.preprocessing import OneHotEncoder

from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn.model_selection import train_test_split

from sklearn.metrics import *
from sklearn import metrics

"""

---

"""

df.columns

x = df.drop(['Date','Weekly_Sales'], axis=1)

x

x.info()

y = df['Weekly_Sales']

rf = RandomForestRegressor(n_estimators = 100)
rf.fit(x, y)
RandomForestRegressor()
# checking the feature importance

plt.figure(figsize = (15, 5))
plt.bar(x.columns, rf.feature_importances_)
plt.title("Feature Importance", fontsize = 15)
plt.show()

x_train, x_test, y_train, y_test = train_test_split(x, y, train_size = 0.8, random_state = 0)

#Linear Regression
lr = LinearRegression()
lr.fit(x_train, y_train)
LinearRegression()
y_pred = lr.predict(x_test)
plt.scatter(y_test, y_pred)

print("R2 Score: ", r2_score(y_test, y_pred))
print("MSE Score: ", mean_squared_error(y_test, y_pred))
print("RMSE : ", sqrt(mean_squared_error(y_test, y_pred)))

#Decision Tree
dtree = DecisionTreeRegressor()
dtree.fit(x_train, y_train)
DecisionTreeRegressor()
y_pred1 = dtree.predict(x_test)
plt.scatter(y_test, y_pred1)

print("R2 Score: ", r2_score(y_test, y_pred1))
print("MSE Score: ", mean_squared_error(y_test, y_pred1))
print("RMSE : ", sqrt(mean_squared_error(y_test, y_pred1)))

#Random Forest
rf1 = RandomForestRegressor(n_estimators = 100)
rf1.fit(x_train, y_train)
RandomForestRegressor()
y_pred2 = rf1.predict(x_test)
plt.scatter(y_test, y_pred2)

print("R2 Score: ", r2_score(y_test, y_pred2))
print("MSE Score: ", mean_squared_error(y_test, y_pred2))
print("RMSE : ", sqrt(mean_squared_error(y_test, y_pred2)))

#KNN
knn = KNeighborsRegressor()
knn.fit(x_train, y_train)
KNeighborsRegressor()
y_pred3 = knn.predict(x_test)
plt.scatter(y_test, y_pred3)

print("R2 Score: ", r2_score(y_test, y_pred3))
print("MSE Score: ", mean_squared_error(y_test, y_pred3))
print("RMSE : ", sqrt(mean_squared_error(y_test, y_pred3)))

#XGBoost

# Specify the features and target variable
features = ['Store', 'Year', 'Month']
target = 'Weekly_Sales'

# Split the data into training and testing sets
x_train, x_test, y_train, y_test = train_test_split(df[features], df[target], test_size=0.2, random_state=42)

# Create and train the XGBoost model with enable_categorical=True
xg = XGBRegressor(n_estimators=100, random_state=42, enable_categorical=True)
xg.fit(x_train, y_train)

# Make predictions on the test set
y_pred4 = xg.predict(x_test)

# Evaluate the model
r2 = r2_score(y_test, y_pred4)
mse = mean_squared_error(y_test, y_pred4)
rmse = np.sqrt(mse)

print("R2 Score: ", r2)
print("MSE Score: ", mse)
print("RMSE Score: ", rmse)

# Plot predicted vs actual values
plt.scatter(y_test, y_pred4)
plt.xlabel("Actual Weekly Sales")
plt.ylabel("Predicted Weekly Sales")
plt.title("XGBoost: Predicted vs Actual Weekly Sales")
plt.show()

# Getting Average of Best Models
y_pred_final = (y_pred1 + y_pred2  + y_pred4)/3.0
plt.scatter(y_test, y_pred_final)

print("R2 Score: ", r2_score(y_test, y_pred_final))
print("MSE Score: ", mean_squared_error(y_test, y_pred_final))
print("RMSE : ", sqrt(mean_squared_error(y_test, y_pred_final)))

# Calculate summary statistics
summary_stats = df.describe()
summary_stats

# Perform statistical tests or correlations
# Example: Calculate correlation between Weekly Sales and Unemployment Rate
correlation = df['Weekly_Sales'].corr(df['Unemployment'])

# Additional statistical tests
# Example: t-test comparing Weekly Sales between two groups (Group_A and Group_B)
group_a_sales = df[df['Holiday_Flag'] == 0]['Weekly_Sales']
group_b_sales = df[df['Holiday_Flag'] == 1]['Weekly_Sales']
t_stat, p_value = stats.ttest_ind(group_a_sales, group_b_sales)

"""Perform t-test"""

# Perform t-test
t_stat, p_value = stats.ttest_ind(group_a_sales, group_b_sales)

# Print the results
print("T-Statistic:", t_stat)
print("P-Value:", p_value)

"""#OR"""

# Perform t-test
#t_stat, p_value = stats.ttest_ind(group_a_sales, group_b_sales)

# Create a DataFrame to display the results
#results_df = pd.DataFrame({'T-Statistic': [t_stat], 'P-Value': [p_value]})

# Display the results
#display(results_df)

#3. Apply time series analysis to identify seasonal trends:

# Use seasonal decomposition to identify seasonal, trend, and residual components
result = sm.tsa.seasonal_decompose(df['Weekly_Sales'], model='additive', period=52)

# Plot the decomposed components
fig, ax = plt.subplots(4, 1, figsize=(20, 40))
result.observed.plot(ax=ax[0])
ax[0].set_ylabel('Observed')
result.trend.plot(ax=ax[1])
ax[1].set_ylabel('Trend')
result.seasonal.plot(ax=ax[2])
ax[2].set_ylabel('Seasonal')
result.resid.plot(ax=ax[3])
ax[3].set_ylabel('Residual')

plt.tight_layout()
plt.show()

#4. Analyze the impact of variables on weekly sales:

# Assuming you have additional variables (unemployment rate, temperature, and CPI) in your dataset

# Create a matrix of independent variables
X = df[['Unemployment', 'Temperature', 'CPI']]

# Add constant to the matrix
X = sm.add_constant(X)

# Fit the multiple linear regression model
model = sm.OLS(df['Weekly_Sales'], X)
results = model.fit()

# Print the model summary
print(results.summary())

#5. Visualize relationships using appropriate plots:

# Scatter plots of the variables against weekly sales
fig, axs = plt.subplots(3, 1, figsize=(20, 10))
axs[0].scatter(df['Unemployment'], df['Weekly_Sales'])
axs[0].set_xlabel('Unemployment Rate')
axs[0].set_ylabel('Weekly Sales')
axs[1].scatter(df['Temperature'], df['Weekly_Sales'])
axs[1].set_xlabel('Temperature')
axs[1].set_ylabel('Weekly Sales')
axs[2].scatter(df['CPI'], df['Weekly_Sales'])
axs[2].set_xlabel('CPI')
axs[2].set_ylabel('Weekly Sales')

plt.tight_layout()
plt.show()

#2. Aggregate the weekly sales data by store and calculate total sales:

# Assuming you have already loaded and preprocessed the Walmart dataset

# Group the dataset by store
df_by_store = df.groupby('Store')['Weekly_Sales'].sum().reset_index()

# Sort the stores based on total sales
df_by_store_sorted = df_by_store.sort_values('Weekly_Sales', ascending=False)

# Print the top 5 best performing stores
print("Top 5 Best Performing Stores:")
print(df_by_store_sorted.head())

# Print Empty Row
print("")

# Print the worst performing stores
print("Top 5 Worst Performing Store:")
print(df_by_store_sorted.tail(5))

#3. Rank the stores based on their historical sales data to identify the top performing stores:

# Add a rank column based on total sales
df_by_store_sorted['Rank'] = np.arange(1, len(df_by_store_sorted) + 1)

# Print the ranked stores
print("Ranked Stores:")
print(df_by_store_sorted)

# Create a new column 'Date' based on the index
df['Date'] = df.index

# If the index is not in the correct date format, convert it to datetime format
df['Date'] = pd.to_datetime(df['Date'])

# Reset the index since we now have the 'Date' column
df.reset_index(drop=True, inplace=True)

# Now, the 'Date' column should be restored in your DataFrame
print(df.head())

df.columns

#2. Load the dataset and preprocess the data:

# Convert the 'Date' column to datetime
df['Date'] = pd.to_datetime(df['Date'])

# Set the 'Date' column as the index
df.set_index('Date', inplace=True)

#3. Split the dataset into training and testing sets:

# Split the dataset into 80% train and 20% test
train_size = int(len(df) * 0.8)
train_data, test_data = df[:train_size], df[train_size:]

#4. Choose a predictive modeling technique:
#- For linear regression:

model = RandomForestRegressor()

#- For time series forecasting, you may use SARIMAX from the statsmodels library. However, this requires additional preprocessing and stationarity checks for the time series.

#5. Implement and train the model:

# Assuming you have selected the predictive modeling technique (e.g., Random Forest)

# Separate the target variable from the features
X_train, y_train = train_data.drop('Weekly_Sales', axis=1), train_data['Weekly_Sales']
X_test, y_test = test_data.drop('Weekly_Sales', axis=1), test_data['Weekly_Sales']

# Fit the model on the training data
model.fit(X_train, y_train)

#6. Evaluate the model's performance:

plt.figure(figsize=(20, 8))

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model using mean squared error (MSE)
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

# Visualize the actual vs. predicted values
plt.plot(y_test.index, y_test.values, label='Actual')
plt.plot(y_test.index, y_pred, label='Predicted')
plt.xlabel('Date')
plt.ylabel('Weekly Sales')
plt.title('Actual vs. Predicted Weekly Sales')
plt.legend()
plt.show()